name: sgr_ticketing
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  provider: ^6.1.2
  supabase_flutter: ^2.6.0
  get: ^4.6.6
  gap: ^3.0.1
  fluentui_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Specify assets here
  assets:
    - assets/images/logo.png
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300

  # If you want to specify this font globally, you can do it in the theme
  # For example, add this in your main.dart file:
  # theme: ThemeData(
  #   fontFamily: 'Poppins',
  # ),
