name: Tikiti
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  provider: ^6.1.2
  supabase_flutter: ^2.6.0
  get: ^4.6.6
  gap: ^3.0.1
  fluentui_icons: ^1.0.0
  carousel_slider: ^5.0.0
  google_fonts: ^6.2.1
  animated_text_kit: ^4.2.2
  intl: ^0.19.0
  shared_preferences: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  intl_utils: ^2.8.7

flutter:
  uses-material-design: true
  generate: true  # Add this line for localization

  assets:
    - assets/icons/trains.png
    - assets/icons/buses.png
    - assets/icons/flights.png
    - assets/icons/home.png
    - assets/icons/search.png
    - assets/icons/hotel.png
    - assets/icons/profile.png
    - assets/icons/saved.png
    - assets/icons/ticket-logo.png 
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300